### PR TITLE
Url integration - pull the hyerlinks to the right (so that it only show up when there exists a url)

### PR DESCRIPTION
**Pull request by yjzhengxiao**
place the urls to the right side of the category, so that it only shows up when there is a url exists

### CODE REVIEW

**Comment by yjzhengxiao** [comment]
This is the corresponding asana task link: https://app.asana.com/0/8548956980512/16772395038309/f

**Comment by WaseemTheDream** [comment]
Hey @yjzhengxiao , how about making the title click-able if it has a link and adding a link icon to the left of the title so that it's obvious that this title can be clicked. 

Look for `glyphicon-link` in this page: http://getbootstrap.com/components/

Also, can you add an analytics event that the link was clicked? That way we can see how many people are actually clicking the links.

**Comment by WaseemTheDream** [comment]
Here is an example of logging an analytics event:
https://github.com/rice-apps/atlas/blob/develop/parse/public/js/controllers/main.js#L26

In the category, specify "result" instead of "search". And call the name of the event, "Click link to Place"

**Comment by WaseemTheDream** [comment]
For your link. See the additional parameters heading here: http://luisfarzati.github.io/angulartics/
You can just add the attributes for the analytics event directly into the link.

**Comment by yjzhengxiao** [comment]
According to John, I need to create pull request with base: develop, instead of base: master. So that I am going to close this one, and switch the new one to the base: develop.

**Comment by yjzhengxiao** [comment]
And the new one is at #12 url integration.

**Pull request closed without merging**
